### ISSUE TITLE
Refine exclude

### ISSUE THREAD

**Issue by melvyn-sopacua** [matthiask/django-js-asset#1]
The setup.py [is excluding tests](https://github.com/matthiask/django-js-asset/blob/3b583bc05b7529f2eac510fd7ce5b929422576c1/setup.py#L25), but not `tests/*` as well, which causes `tests/testapp` to be installed as `testapp`:

    yes n | pip uninstall django-js-asset|grep testapp |tail -1
  /home/melvyn/.local/py-env/testbed/lib/python3.6/site-packages/testapp/urls.py

**Comment by matthiask** [comment]
Thanks for the report! 

This repository does not seem to have a `testapp/urls.py` file, but for example https://github.com/matthiask/django-admin-ordering/ does. Can I ask you to look inside the file to determine which package installs the `testapp` app?

My understanding of `exclude` is that excluding `tests` should be sufficient to also exclude contained packages, but maybe that's not correct.

**Comment by melvyn-sopacua** [comment]
You're absolutely right. The `pip uninstall` command will also uninstall packages required by it, and so this one is fine, but django-admin-ordering isn't. Sorry for the noise.
