### ISSUE TITLE
Compatible versions of Django 

### ISSUE THREAD

**Issue by djowett** [matthiask/django-js-asset#2]
Just wondering which versions of Django you believe this works with?
We are particularly interested to know if 1.8 works (though we've not spotted any issues in dev).

I ask this because `setup.py` hints that you may have once thought that 1.9 was a minimum version at some time.

```
 install_requires=[
        # 'Django>=1.9',
],
```

Thanks!

**Comment by matthiask** [comment]
Hey,

This line was copied over from some other project (probably django-content-editor, but I'm not sure)

The released version (0.1.1) supports Django 1.7 to Django 2.1 with the same code base; the `.travis.yml` file is probably the best place to find out about compatibility: https://github.com/matthiask/django-js-asset/blob/master/.travis.yml resp. https://travis-ci.org/matthiask/django-js-asset/

**Comment by djowett** [comment]
Ok, that's great. 

Thanks

**Comment by matthiask** [comment]
Btw, I just put out a 1.0 release to make it clearer that I consider this project production-ready.

Thanks!
