### ISSUE TITLE
Release the package with Django 3.2 support

### ISSUE THREAD

**Issue by Jawayria** [matthiask/django-js-asset#8]
Hey, we are working on upgrading edX codebase to Django 3.2. This package is being used in the codebase but it isn't yet released with Django 3.2 support. Kindly consider releasing it with Django 3.2 support.
Thanks

**Comment by matthiask** [comment]
Hi @Jawayria 

The package is compatible with Django 3.2 and even with the upcoming Django 4.0. The only thing which has changed since 1.2.2 is the tests, the CI environment and some configuration.

**Comment by matthiask** [comment]
(The last code change to the relevant `js_asset/` folder happened in February 2019.)
